SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE USER IF EXISTS;
CREATE TABLE USER (
  userId INTEGER IDENTITY,
  name VARCHAR(255) NOT NULL,
  login VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  amount NUMERIC NOT NULL,
  managerId INTEGER NOT NULL,
  role VARCHAR(255) NOT NULL,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedDate TIMESTAMP NOT NULL
);
